### ISSUE TITLE
Description on Github doesn't give much information

### ISSUE THREAD

**Issue by mlms13** [fponticelli/thx.core#110]
![screen shot 2015-11-13 at 10 11 56 am](https://cloud.githubusercontent.com/assets/1105543/11152473/f7807a34-89ef-11e5-85da-3e53dedfeec2.png)

This is the text that shows up on [the trending page](https://github.com/trending?l=haxe&since=weekly), which means that the countless people discovering thx for the first time won't know what to expect.

**Comment by fponticelli** [comment]
I think you should improve the documentation :)

**Comment by fponticelli** [comment]
it is done
