### ISSUE TITLE
thx.fp.Map remove or delete method

### ISSUE THREAD

**Issue by andypellucid** [fponticelli/thx.core#116]
Please sir, I humbly request a delete/remove method to remove a key from a thx.fp.Map.

https://hackage.haskell.org/package/containers-0.1.0.1/docs/src/Data-Map.html#delete

I started to work on it in a PR, but it was more than a couple lines of code to add (glue, etc. helper methods), so I stopped.

**Comment by fponticelli** [comment]
I'll see what I can do :)

**Comment by fponticelli** [comment]
It has been done, please verify and close if found suitable.
