### ISSUE TITLE
DateTimeUtc is worse at parsing strings than DateTime

### ISSUE THREAD

**Issue by mlms13** [fponticelli/thx.core#132]
If you convert a `DateTime` value to a string, then later try to parse that string value using `DateTimeUtc.fromString()`, the [parsing will fail](http://try.thx-lib.org/#C5d81).

Regular `DateTime`s are happy to work with strings that look like this: "2015-12-21T11:35:22.4960000-07:00", but the `Utc` version is very unhappy with extra timezone information.

Would it make sense to replace [the internals of DateTimeUtc's `fromString`](https://github.com/fponticelli/thx.core/blob/master/src/thx/DateTimeUtc.hx#L90-L113) with a call to DateTime's `fromString` instead?  Something like:

```haxe
public static function fromString(s : String) : DateTimeUtc {
  return DateTime.fromString(s).utc;
}
```

Will that do weird and bad things if the timezone is omitted completely? Dates are the worst.

**Comment by fponticelli** [comment]
followed your suggestion and changed to use `DateTime.fromString`.
