### ISSUE TITLE
Incorrect Decimal output

### ISSUE THREAD

**Issue by azrafe7** [fponticelli/thx.core#180]
Unless I'm doing something wrong this snippet reports an incorrect result (at least on http://try.thx-lib.org/#70AD8) when using Decimal, but works with Float:
```haxe
import thx.Decimal;

typedef Dec = Decimal;
//typedef Dec = Float;

class Test {
  static function main() {
    
    var color:Dec = 4;
    var alpha:Dec = 32;
    var mult:Dec = color * alpha / (255 : Dec);
    
    var unmult:Dec = (255 : Dec) * mult / alpha;
    
    trace(mult);
    trace(unmult);
    trace(unmult == color);
  }
}
```

Haven't tested it yet with the git version of the lib.

**Comment by fponticelli** [comment]
I am not sure what you would expect differently. When you divide by 255 your fraction contains infinite decimals. That is something that `Decimal` needs to round and by default it adds at most 4 decimal positions to the dividend. When you multiply back you get the right result. You can reduce the problem by adding more decimals to the dividend like follows:
```haxe
    var a:Dec = "4.00000000000000";
    var b:Dec = 255;
    trace(a/b);
    trace(a/b*b);
```

But this will mitigate and not resolve the issue. If you do the same with floats you will still get an error, just a different approximation error.

To mitigate the issue you can round your results or if you really want super precision you might want to build a type for rational numbers (a PR to thx.core for that would be very welcome).

**Comment by azrafe7** [comment]
Ah... I see it now, thanks for the explanation.
In this case Float gave the exact result by chance.

> by default it adds at most 4 decimal positions to the dividend

Is there a way to increase that precision programmatically?

**Comment by fponticelli** [comment]
Yes, there are 2 ways to do it:

 - generate the value from a format that has notion of the number of decimals like importing from a string: `var a:Decimal = "4.00000000000000";`
 - set `Decimal.divisionScale` and all divisions will use that extra number of decimals

To be honest there is a `divideWithScale` here https://github.com/fponticelli/thx.core/blob/master/src/thx/bigint/DecimalImpl.hx#L40 and it really should be exposed in the abstract. I will add a ticket for it.

**Comment by azrafe7** [comment]
Great, thanks for the info.
