### ISSUE TITLE
Usability in Macro Context

### ISSUE THREAD

**Issue by 0b1kn00b** [fponticelli/thx.core#194]
Would I be free to unpick, for example, `fp.List` so that it works in the macro context? right now it chokes on the `fn` when used. What's your policy there?

**Comment by fponticelli** [comment]
Go for it. `fn` is a nice convenience but if it gets us into troubles (macros in macros) it is ok to remove its usage from the lib. It still has a lot of value for library users.

**Comment by 0b1kn00b** [comment]
pull request #195
