### ISSUE TITLE
[ReadonlyArray] reduce inconsistency

### ISSUE THREAD

**Issue by profelis** [fponticelli/thx.core#237]
Hi! Something wrong in this 2 methods
https://github.com/fponticelli/thx.core/blob/master/src/thx/ReadonlyArray.hx#L49-L62

First reduce shoud be static too? Or just iterate this in boths methods and remove static accessor from second? 😄

**Comment by fponticelli** [comment]
Definitely inconsistent. They should be non-static and operate from the internal array. Thank you!
