### ISSUE TITLE
Haxe 4?

### ISSUE THREAD

**Issue by hamaluik** [fponticelli/thx.core#255]
Are there plans / is there an effort to update this to the forthcoming v4.0 of Haxe? Right now, running the tests with haxe 4.0.0-preview.2 results in a litany of errors (https://gist.github.com/FuzzyWuzzie/80bb02775c5e807d872eb36bd89c5f45).

This doesn't seem to be a trivial update, though it will eventually be necessary. Are there currently plans to update the library? Or are you waiting until v4 is more stable? Can we help in any way, and if so—what's the best way?

Thanks!

**Comment by fponticelli** [comment]
Things might have changed in the latest release. We are using an earlier version of 4 with no errors. It is very likely that these errors will be addressed but at the moment I personally do not have time for fixes. Hopefully soon. PRs are always welcome.

**Comment by fponticelli** [comment]
should be fixed
