### ISSUE TITLE
thx.core.QueryString ?

### ISSUE THREAD

**Issue by fponticelli** [fponticelli/thx.core#37]
https://nodejs.org/api/querystring.html

**Comment by jasononeil** [comment]
I'm using this:

http://api.ufront.net/ufront/core/MultiValueMap.html
https://github.com/ufront/ufront-mvc/blob/master/src/ufront/core/MultiValueMap.hx

Which I read from a query string using something like this:

https://github.com/ufront/ufront-mvc/blob/master/src/neko/ufront/web/context/HttpRequest.hx#L302

*In case you're interested...*

**Comment by fponticelli** [comment]
argh ... only now I see your comments and your multivaluemap looks very similar to my implementation. So similar that I wonder if I should add MultiValueMap to core and refactor using it.

**Comment by jasononeil** [comment]
Haha don't you hate it when that happens.

If there's anything you want me to do to make MultiValueMap more suitable for bundling in thx, let me know.

**Comment by fponticelli** [comment]
Are you using it anywhere else?

**Comment by jasononeil** [comment]
I use it in a few places through ufront-mvc, mostly just to manage request.query, request.post, request.cookies and request.params (the combination of the 3).

Other than that I use it in a few personal projects.  If you want to implement something similar but with a slightly different API, I don't mind breaking compatibility if you do it in the next month or so.  After that I'd like to lock down a "stable" version without API changes though.

**Comment by fponticelli** [comment]
I will try doing it this weekend.
