### ISSUE TITLE
convert AnonymousMap to StringMap

### ISSUE THREAD

**Issue by francescoagati** [fponticelli/thx.core#42]
Hi,
i am trying to convert AnonymousMap<String> to StringMap<String> but i get an error compile.
What is wrong? AnonymousMap implements IMap<String,V>

this is the code example

```
var params:StringMap<String> =   new AnonymousMap<String>(Json.parse('{"a":1,"b":2,"c":3}'));
```
and this the error

 thx.core.AnonymousMap<String> should be haxe.ds.StringMap<String>

**Comment by fponticelli** [comment]
Unfortunately I don't think it is doable. StringMap is special. If you inspect the code generated you will see that it is highly optimized with the inlining of many methods. As such it cannot be extended so AnonymousMap is a `Map<String, T>` but cannot be a `StringMap<T>`.
My suggestion is to use `thx.core.Objects. objectToMap(Json.parse('{"a":1,"b":2,"c":3}'))` to convert your object to a `StringMap`. If you find a better solution feel free to reopen ;)

**Comment by francescoagati** [comment]
Thanks Franco. I have resolved with a simple loop conversion.
