### ISSUE TITLE
strange problem with types and groupBy Function

### ISSUE THREAD

**Issue by francescoagati** [fponticelli/thx.core#45]
Hi,
with groupBy and Dynamic i have a strange problem with types

with this code 

```
 function group_panel_selected() {
    var panels:Array<Dynamic> = untyped scope.panels;
     return panels.groupBy(function(el) {
      return el.level;
    });
  }
```

i get this error 

```
  Could not determine type for parameter TKey
  Missing return Map<Unknown<0>, Array<{ level : Unknown<0> }>>

```

if i try to force the return type to Int how in this example

```
function group_panel_selected() {
    var panels:Array<Dynamic> = untyped scope.panels;
     return panels.groupBy(function(el) {
      return (el.level:Int);
    });
  } 
```

i get 

```
Type parameter must be a class or enum instance (found { level : Int })
Missing return Map<Int, Array<{ level : Int }>>
```

What is the right solution for using groupBy with Dynamics?

**Comment by fponticelli** [comment]
Can you try the following?

```haxe
 function group_panel_selected() {
    var panels:Array<{ level : Int }> = untyped scope.panels;
     return panels.groupBy(function(el) {
      return el.level;
    });
  }
```

**Comment by francescoagati** [comment]
tryed but return this error 

```
Type parameter must be a class or enum instance (found { level : Int })
Missing return Map<Int, Array<{ level : Int }>>
```

**Comment by fponticelli** [comment]
I can't see why the compiler should enforce such restriction since the method is `@:generic` and `Int` is a legit type for the `key` of the map ... a hole in the type system?
I certainly never tested it with `Dynamic` and you never know what you face when you use it :(

**Comment by fponticelli** [comment]
also, since you are apparently using thx, have a look at this before it hits you badly :)  https://github.com/fponticelli/thx.core/issues/45

**Comment by francescoagati** [comment]
i am using haxe 3.1
i don't understand why:  return Type parameter must be a class or enum instance

**Comment by fponticelli** [comment]
Me neither, I wonder if it compiles fine on 3.2.

**Comment by fponticelli** [comment]
Sorry, the issue referred before was supposed to be #44

**Comment by francescoagati** [comment]
i am using thx.core: 0.17.4 [0.18.0]

**Comment by francescoagati** [comment]
the git version is 0.19

**Comment by fponticelli** [comment]
The error is the same on 3.2

**Comment by fponticelli** [comment]
I tested it with arrays and class instances and it works just fine. I fear that `@:generic` doesn't support anonymous objects and that rules your case out :(
Also we cannot remove `@:generic` because `Map` cannot be dynamically constructed. The only solution I see is to create another function that receives the same parameters + the map. It should work that way.

**Comment by fponticelli** [comment]
If you now use `groupByAppend` you should be good ;)

**Comment by francescoagati** [comment]
thanks i try it
