### ISSUE TITLE
strange error with regular expression in macro

### ISSUE THREAD

**Issue by francescoagati** [fponticelli/thx.core#50]
In 2 linux installation i get this error 

```
/usr/lib/haxe/std/neko/_std/EReg.hx:33: characters 11-61 : Unsupported escaped char 's'
<builtin>:1: character 0 : Called from
/usr/lib/haxe/std/neko/_std/EReg.hx:22: lines 22-204 : Called from
/usr/lib/haxe/lib/thx,core/0,20,0/src/thx/Strings.hx:394: characters 25-36 : Called from
Aborted
```

but the error occure randomly in different linux instantiation. May depends from neko installation pecl?

**Comment by fponticelli** [comment]
is line 394 this? `static var UCWORDSWS = ~/\s[a-z]/g;`
We can easily change `\s` to `[ ]` and I suspect you are right about PECL.

**Comment by francescoagati** [comment]
yes this line but i don't understant why in some haxe installation thx.core work and in others don't work.
I have find the same problem also in other issue.
For example this https://github.com/ufront/hello/issues/5.

**Comment by francescoagati** [comment]
with this changes 
```
  static var UCWORDSWS = ~/\[ ][a-z]/g;
  static var ALPHANUM = ~/^[a-z0-9]+$/i;
  static var DIGITS = ~/^[0-9]+$/;
  static var STRIPTAGS = ~/<\/?[a-z]+[^>]*?\/?>/gi;
```
i get now
```
/usr/lib/haxe/std/neko/_std/EReg.hx:33: characters 11-61 : Ungreedy *? are not supported in macros
<builtin>:1: character 0 : Called from
/usr/lib/haxe/std/neko/_std/EReg.hx:22: lines 22-204 : Called from
/usr/lib/haxe/lib/thx,core/0,20,0/src/thx/Strings.hx:397: characters 25-50 : Called from

```

**Comment by francescoagati** [comment]
the line 397 is ```
  static var STRIPTAGS = ~/<\/?[a-z]+[^>]*?\/?>/gi;
```

**Comment by francescoagati** [comment]
modify this code now complie 

```
  static var UCWORDS = ~/[^a-zA-Z]([a-z])/g;
#if !php
  static var UCWORDSWS = ~/\[ ][a-z]/g;  //modify
  static var ALPHANUM = ~/^[a-z0-9]+$/i;
  static var DIGITS = ~/^[0-9]+$/;
  static var STRIPTAGS = ~/<\/?[a-z]+[^>].+\/?>/gi; //modify
#end
  static var WSG = ~/\[ ]+/g;  //modify
  static var SPLIT_LINES = ~/\r\n|\n\r|\n|\r/g;
```
line modified are 394,397, and 399

i don't know if striptags is correct. i have replace *? with .+

**Comment by fponticelli** [comment]
`\[ ]` is not right ... it should be `[ ]` and probably even better: `[ \t\r\n\f]`

**Comment by fponticelli** [comment]
I just made a commit with the replacements .... can you check it works for you?

**Comment by francescoagati** [comment]
this works.rest the error on the striptags regexp

```
/usr/lib/haxe/std/neko/_std/EReg.hx:33: characters 11-61 : Ungreedy *? are not supported in macros
<builtin>:1: character 0 : Called from
/usr/lib/haxe/std/neko/_std/EReg.hx:22: lines 22-204 : Called from
/usr/lib/haxe/lib/thx,core/git/src/thx/Strings.hx:405: characters 25-50 : Called from
```
https://github.com/fponticelli/thx.core/blob/master/src/thx/Strings.hx#L405

**Comment by fponticelli** [comment]
Should be ok now.

**Comment by francescoagati** [comment]
WORKS! Thanks Franco :-)

**Comment by fponticelli** [comment]
No problem ;)

**Comment by francescoagati** [comment]
I don't understand why in some haxe installation there is this problem with regexp and in other no.

**Comment by fponticelli** [comment]
Same kind of issues or different?

Il giorno ven 8 mag 2015 alle ore 13:56 francesco agati <
notifications@github.com> ha scritto:

**Comment by francescoagati** [comment]
Regalar expression in macro
See this http://old.haxe.org/forum/thread/3395#nabble-td6680244

Il sabato 9 maggio 2015, Franco Ponticelli <notifications@github.com> ha
scritto:

**Comment by fponticelli** [comment]
:(

Il giorno ven 8 mag 2015 alle ore 17:08 francesco agati <
notifications@github.com> ha scritto:

**Comment by francescoagati** [comment]
For this first i have asc if my problem was Pecl regular expression

Il sabato 9 maggio 2015, Franco Ponticelli <notifications@github.com> ha
scritto:
