### ISSUE TITLE
All static extensions in a single class for using?

### ISSUE THREAD

**Issue by TiZ-EX1** [fponticelli/thx.core#81]
Hi there. I'd like to have a single class I can do using on in order to get all the static extensions this library offers. I was trying to figure out what it is you did in Strings.hx that caused it to also have the StringTools methods so I could make this class myself, but I couldn't figure it out.

Thanks.

**Comment by fponticelli** [comment]
With the latest version of the library you should be able to do `using Thx;` and get all the goodness of the library. Let me know if that solves your issue.

**Comment by TiZ-EX1** [comment]
When I compile, I get an error.

    $ haxe -main ParseHTML -lib thx.core -cpp .cpp.bld
    /usr/lib/haxe/std/neko/_std/EReg.hx:33: characters 11-61 : Unsupported escaped char 's'
    <builtin>:1: character 0 : Called from
    /usr/lib/haxe/std/neko/_std/EReg.hx:22: lines 22-204 : Called from
    /home/tiz/.local/share/haxelib/thx,core/0,35,0/src/thx/Ints.hx:11: characters 29-59 : Called from
    Aborted

Which is weird to me because \s is for whitespace...

**Comment by fponticelli** [comment]
That is strange, my test pass for both haxe 3.2.0 and dev. Does that happen when you use `using Thx;` or when you do `using thx.Ints;`? Or in both cases? Do you think you can try to reproduce the issue here? http://try.thx-lib.org/

**Comment by TiZ-EX1** [comment]
I googled the issue, and funnily enough, found #50. Maybe they're related? Anyways, it only manifested with Thx, not with thx.Ints. I changed the regex in line 11 of Ints.hx to this: `~/^[ \t\r\n]*[+-]?(\d+|0x[0-9A-F]+)/i` That allowed it to compile. I wonder why that breaks in Thx but not in thx.Ints.

Though I found a different issue by doing tests on the website; when you use thx.Strings, you get StringTools, but when you use Thx, you don't get StringTools. Test case for website:

    using Thx;
    
    class Test {
      static function main() {
        trace("thxIsGreat!".startsWith("thx"));
        trace(2.isEven());
      }
    }

That one I was able to fix by adding `typedef HaxeStringTools = StringTools;` right below the Strings line.

Is that how that works? typedef causes them all to get pulled in? Interesting.

**Comment by fponticelli** [comment]
Macros ... I will apply the fix.

Il giorno gio 8 ott 2015 alle ore 10:19 Trent McPheron <
notifications@github.com> ha scritto:

**Comment by fponticelli** [comment]
Please let me know if the fix in git solves your issue.

**Comment by TiZ-EX1** [comment]
That solves the compile error related to Ints, but still doesn't pull StringTools along with thx.Strings.

**Comment by fponticelli** [comment]
correct, I forgot about that ... will do that now

Il giorno gio 8 ott 2015 alle ore 20:16 Trent McPheron <
notifications@github.com> ha scritto:

**Comment by fponticelli** [comment]
Should be done.

**Comment by TiZ-EX1** [comment]
It's all fixed. Thanks, boss! :+1:

**Comment by fponticelli** [comment]
Thank you and I will try to make a release asap
