### ISSUE TITLE
Would a `HashSet` class/abstract make sense in thx.core?

### ISSUE THREAD

**Issue by andywhite37** [fponticelli/thx.core#92]
It looks like the `thx.Set<T>` abstract wraps a `Map<T, Bool>` where the map key stores the set values.  I think this means that checking for set existence uses `==` to compare items.

Would it make sense to add a `thx.HashSet<T>` abstract wrapping a `HashMap<T, Bool>`, so that you can provide a `hashCode` method on T to use for set existence?  I would like to use `Set`, but I can't because I can't use `==` for comparing set items.

Or is there another way to achieve this?

I can submit a PR for `HashSet` if you like that idea.

**Comment by fponticelli** [comment]
Using an object as a key should be quite efficient. What happens for most platforms (all?) is that on first usage a new hidden field is added to the object (an ID) and used as the real key for the Map. Not sure if it worth investing in a proper hashcode implementation.

**Comment by andypellucid** [comment]
I'm not too worried about efficiency, the problem I have is that I will have set objects that are not `==`, but they need to be treated as the same value in the set.  E.g. `{ ns: "ns1", id: "some-id" }` and `{ ns: "ns1", id: "some-id" }`, are distinct objects and are not `==`, but I want them to be treated as the same value in the set.  I think this would require a HashSet, or something that allows the type to specify a hash code to check equality.
